import React from 'react';
import {
  FileText,
  AlertOctagon,
  CheckCircle,
  XCircle,
  Clock,
  MapPin,
  Car,
  User,
  Phone,
  Download,
  RotateCcw,
  ShieldCheck,
  Ambulance,
  Shield,
  PhoneCall,
  ExternalLink,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { SimulatedCameraFeed } from '../components/SimulatedCameraFeed';
import { ConfidenceRing } from '../components/ConfidenceRing';
import { HorizontalResponseTimeline } from '../components/HorizontalResponseTimeline';

export const IncidentDetailsPage: React.FC = () => {
  const {
    activeIncident,
    updateIncidentStatus,
    replayIncidentTimeline,
    setNotificationPreview,
  } = useApp();

  const inc = activeIncident;

  if (!inc) {
    return (
      <div className="p-8 text-center bg-slate-900 border border-slate-800 rounded-2xl">
        <FileText className="w-12 h-12 text-slate-500 mx-auto mb-3" />
        <h3 className="text-base font-bold text-white">No Incident Selected</h3>
        <p className="text-xs text-slate-400 mt-1">
          Select an incident from the Dashboard, Live Monitoring, or Incident History page.
        </p>
      </div>
    );
  }

  const handleDownloadReport = () => {
    const reportData = {
      incident_id: inc.incident_id,
      timestamp: inc.timestamp,
      location: inc.location,
      coordinates: { lat: inc.latitude, lng: inc.longitude },
      camera: inc.camera_id,
      ai_confidence: inc.confidence,
      verification_status: inc.verification_status,
      accident_type: inc.accident_type,
      vehicles_involved: inc.vehicle_count,
      plate_number: inc.plate_number,
      vehicle_details: inc.vehicle_details,
      emergency_dispatches: {
        ambulance: inc.ambulance_status,
        police: inc.police_status,
        family_sms: inc.family_status,
      },
      audit_note: 'Generated by JeevanSetu AI Autonomous Incident Intervention System (Demo Environment)',
    };

    const blob = new Blob([JSON.stringify(reportData, null, 2)], {
      type: 'application/json',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${inc.incident_id}_incident_report.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleViewSMS = () => {
    setNotificationPreview({
      open: true,
      recipient: inc.vehicle_details?.emergency_contact || '+91 98765 43210',
      plate: inc.plate_number,
      message: `Emergency alert: A possible accident involving registered vehicle ${inc.plate_number} has been detected near ${inc.location}. Emergency responders have been notified. (Simulated Demo)`,
    });
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Top Incident Header & Status Toolbar */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-mono font-bold bg-slate-950 px-2.5 py-1 rounded-lg border border-slate-800 text-slate-300">
              {inc.incident_id}
            </span>
            <span
              className={`text-xs font-mono font-bold px-2.5 py-1 rounded-lg border ${
                inc.incident_status === 'ACTIVE'
                  ? 'bg-rose-500/10 text-rose-400 border-rose-500/30 animate-pulse'
                  : inc.incident_status === 'RESOLVED'
                  ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30'
                  : inc.incident_status === 'FALSE_ALARM'
                  ? 'bg-slate-800 text-slate-400 border-slate-700'
                  : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
              }`}
            >
              STATUS: {inc.incident_status}
            </span>
            <span className="text-xs font-mono text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-lg border border-emerald-500/20">
              AI Confidence: {inc.confidence}% (VERIFIED)
            </span>
          </div>

          <h2 className="text-xl font-extrabold text-white tracking-tight mt-2">
            {inc.accident_type} at {inc.location}
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Detected via Camera {inc.camera_id} • Latency to emergency dispatch: 8 seconds
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            onClick={() => replayIncidentTimeline(inc)}
            className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl border border-slate-700 transition-colors flex items-center space-x-1.5 cursor-pointer"
          >
            <RotateCcw className="w-3.5 h-3.5 text-sky-400" />
            <span>Replay Timeline</span>
          </button>

          <button
            onClick={handleDownloadReport}
            className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl border border-slate-700 transition-colors flex items-center space-x-1.5 cursor-pointer"
          >
            <Download className="w-3.5 h-3.5 text-emerald-400" />
            <span>Download Report (JSON)</span>
          </button>

          {inc.incident_status !== 'RESOLVED' && (
            <button
              onClick={() => updateIncidentStatus(inc.id, 'RESOLVED')}
              className="px-3.5 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-md transition-colors flex items-center space-x-1.5 cursor-pointer"
            >
              <CheckCircle className="w-3.5 h-3.5" />
              <span>Mark Resolved</span>
            </button>
          )}

          {inc.incident_status !== 'FALSE_ALARM' && (
            <button
              onClick={() => updateIncidentStatus(inc.id, 'FALSE_ALARM')}
              className="px-3.5 py-2 bg-slate-800 hover:bg-slate-700 text-slate-400 hover:text-rose-300 text-xs font-semibold rounded-xl border border-slate-700 transition-colors flex items-center space-x-1.5 cursor-pointer"
            >
              <XCircle className="w-3.5 h-3.5" />
              <span>False Alarm</span>
            </button>
          )}
        </div>
      </div>

      {/* Grid: Camera Optical Frame Snapshot & Detection Telematics */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Optical Frame Visualizer */}
        <div className="lg:col-span-7 space-y-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl">
            <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-800 text-xs">
              <span className="font-bold text-white flex items-center space-x-2">
                <span className="w-2 h-2 rounded-full bg-rose-500 animate-ping" />
                <span>Camera {inc.camera_id} Optical Snapshot & OCR Frame</span>
              </span>
              <span className="font-mono text-slate-400">Timestamp: {inc.timestamp}</span>
            </div>

            <SimulatedCameraFeed
              cameraId={inc.camera_id}
              cameraName={inc.location}
              isAccident={true}
              stage={8}
              height="h-72 sm:h-80"
              showControls={true}
            />
          </div>

          {/* Explainable AI Confidence Ring */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl flex flex-col sm:flex-row items-center gap-6">
            <div className="shrink-0 flex flex-col items-center">
              <ConfidenceRing score={inc.confidence} size={110} strokeWidth={8} />
            </div>

            <div className="space-y-1.5 text-xs">
              <h4 className="text-sm font-bold text-white">Explainable Neural Network Breakdown</h4>
              <p className="text-slate-400 leading-relaxed">
                The optical analysis system detected a sharp decelerative collision vector (0.88G) with bounding-box overlap that persisted over 16 sequential video frames.
              </p>
              <div className="pt-2 flex flex-wrap gap-2">
                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-mono text-[11px]">
                  ✓ Trajectory Divergence
                </span>
                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-mono text-[11px]">
                  ✓ Box IoU Overlap &gt; 0.65
                </span>
                <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-mono text-[11px]">
                  ✓ Optical Flow Anomaly
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Vehicle & Emergency Dispatch Status */}
        <div className="lg:col-span-5 space-y-6">
          {/* Vehicle & Owner Info Card (Section 12) */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl">
            <div className="flex items-center justify-between pb-3 mb-4 border-b border-slate-800">
              <div className="flex items-center space-x-2">
                <Car className="w-4 h-4 text-sky-400" />
                <h3 className="text-sm font-bold text-white">Vehicle & Owner Telematics</h3>
              </div>
              <span className="text-[10px] font-mono text-sky-400 bg-sky-500/10 px-2 py-0.5 rounded border border-sky-500/20">
                ANPR Matched
              </span>
            </div>

            <div className="space-y-3 text-xs">
              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 flex items-center justify-between">
                <span className="text-slate-400">License Plate (HSRP)</span>
                <span className="font-mono text-base font-black text-sky-300">
                  {inc.plate_number}
                </span>
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="p-2.5 bg-slate-950 rounded-xl border border-slate-800">
                  <span className="text-[11px] text-slate-400 block">Vehicle Model</span>
                  <span className="font-semibold text-white">
                    {inc.vehicle_details?.model || 'Maruti Suzuki Dzire (White)'}
                  </span>
                </div>

                <div className="p-2.5 bg-slate-950 rounded-xl border border-slate-800">
                  <span className="text-[11px] text-slate-400 block">Registered Owner</span>
                  <span className="font-semibold text-white">
                    {inc.vehicle_details?.owner_name || 'Rajesh Sharma'}
                  </span>
                </div>
              </div>

              <div className="p-3 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
                <span className="text-[11px] text-slate-400 flex items-center">
                  <Phone className="w-3.5 h-3.5 mr-1 text-emerald-400" />
                  Registered Emergency Contact
                </span>
                <div className="flex items-center justify-between font-mono">
                  <span className="text-white font-bold">
                    {inc.vehicle_details?.contact_name || 'Kavita Demo (Spouse)'}
                  </span>
                  <span className="text-emerald-400 font-bold">
                    {inc.vehicle_details?.emergency_contact || '+91 98765 43210'}
                  </span>
                </div>
              </div>

              <button
                onClick={handleViewSMS}
                className="w-full py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold rounded-xl border border-slate-700 transition-colors flex items-center justify-center space-x-1.5 cursor-pointer"
              >
                <ExternalLink className="w-3.5 h-3.5 text-emerald-400" />
                <span>View Dispatched SMS Message</span>
              </button>
            </div>
          </div>

          {/* Emergency Dispatches Status */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 shadow-xl">
            <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-800">
              <h3 className="text-sm font-bold text-white">Autonomous Response Status</h3>
              <span className="text-[10px] text-slate-400 font-mono">Simultaneous Dispatch</span>
            </div>

            <div className="space-y-3 text-xs">
              <div className="flex items-center justify-between p-2.5 bg-slate-950 rounded-xl border border-slate-800">
                <div className="flex items-center space-x-2">
                  <Ambulance className="w-4 h-4 text-amber-400" />
                  <span className="text-slate-200 font-semibold">Ambulance (108)</span>
                </div>
                <span className="font-mono text-amber-400 font-bold">
                  {inc.ambulance_status}
                </span>
              </div>

              <div className="flex items-center justify-between p-2.5 bg-slate-950 rounded-xl border border-slate-800">
                <div className="flex items-center space-x-2">
                  <Shield className="w-4 h-4 text-blue-400" />
                  <span className="text-slate-200 font-semibold">Police Patrol</span>
                </div>
                <span className="font-mono text-blue-400 font-bold">
                  {inc.police_status}
                </span>
              </div>

              <div className="flex items-center justify-between p-2.5 bg-slate-950 rounded-xl border border-slate-800">
                <div className="flex items-center space-x-2">
                  <PhoneCall className="w-4 h-4 text-emerald-400" />
                  <span className="text-slate-200 font-semibold">Family SMS SOS</span>
                </div>
                <span className="font-mono text-emerald-400 font-bold">
                  {inc.family_status}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Latency Response Timeline */}
      <HorizontalResponseTimeline incident={inc} />
    </div>
  );
};
